spring.application.name=google-leads-transmitter
spring.profiles.active=dev

server.port=8140
server.servlet.context-path=/api

smartmoving.provider-key=${SMARTMOVING_PROVIDER_KEY:2e5a794b-763f-400d-893d-b09f01382a0c}
smartmoving.referral-source=Google Ads
