spring.application.name=google-leads-transmitter
spring.profiles.active=prod

server.port=8140
server.servlet.context-path=/api

smartmoving.provider-key=2e5a794b-763f-400d-893d-b09f01382a0c

google.account.timezone=America/New_York
google.referral-source=Google Ads
google.developer-token=kl_z8Dr2OBSoDf8oz-TOsA
google.client-id=960595281067-df49tkdouo85i6cf7992a2uvqbf0jmjo.apps.googleusercontent.com
google.customer-ids=2595930533,2223075774,6958309795
google.client-secret=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
google.refresh-token=1//03K81KRYtudf1CgYIARAAGAMSNwF-L9IrjemfLxNXJZPKrGH9VsWRZvPeb-EIE0fy0dWMwG5L_5ZwV0B0n0pCAe9--uuywsbhd2k

data-sync.interval=300000