spring.application.name=google-leads-transmitter
spring.profiles.active=prod

server.port=8140
server.servlet.context-path=/api

smartmoving.provider-key=${SMARTMOVING_PROVIDER_KEY}

google.account.timezone=America/Los_Angeles
google.referral-source=Google Local Services
google.developer-token=${GOOGLE_DEVELOPER_TOKEN}
google.client-id=${GOOGLE_CLIENT_ID}
google.login-customer-id=3302313884
google.customer-ids=2595930533,2223075774,6958309795
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.refresh-token=${GOOGLE_REFRESH_TOKEN}

data-sync.interval=86400000

lead.default.name=Google Customer

