version: '3.8'

networks:
  vlad-iglin-app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  google-leads-app:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - vlad-iglin-app
    depends_on:
      - google-leads-mongodb

  google-leads-mongodb:
    env_file:
      - .env
    image: 'mongo:latest'
    networks:
      - vlad-iglin-app
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - vlad-iglin-data:/data/db

volumes:
  vlad-iglin-data: